blank_issues_enabled: false
contact_links:
  - name: ğŸŒ TextSound Saver Official Website
    url: https://wangchujiang.com/TextSoundSaver/
    about: Introduction to the TextSound Saver app on the official website!